import Header from '@/components/Header'
import Footer from '@/components/Footer'

export const metadata = { title: 'Disclaimer — ClaimPilot' }

export default function DisclaimerPage() {
  return (
    <div className="min-h-screen flex flex-col">
      <Header />
      <main className="flex-1 py-12 px-4">
        <div className="max-w-3xl mx-auto">
          <h1 className="text-3xl font-bold text-[#1a2744] mb-2">Disclaimer</h1>
          <p className="text-gray-400 text-sm mb-8">Last updated: June 2025</p>

          <div className="bg-amber-50 border border-amber-200 rounded-xl p-6 mb-8">
            <h2 className="text-lg font-bold text-amber-800 mb-2">Important Notice</h2>
            <p className="text-amber-700">
              ClaimPilot is a document preparation service, not a legal or regulated insurance service.
            </p>
          </div>

          <h2 className="text-xl font-bold text-[#1a2744] mt-8 mb-3">Document preparation only</h2>
          <p className="text-gray-700 mb-4">
            ClaimPilot generates documentation to help you communicate with your insurer. Our service is limited to
            document preparation based on information you provide. We do not provide legal advice, insurance advice,
            claims management services, or regulated financial advice of any kind.
          </p>

          <h2 className="text-xl font-bold text-[#1a2744] mt-8 mb-3">AI-generated content</h2>
          <p className="text-gray-700 mb-4">
            The analysis and documents generated by ClaimPilot use artificial intelligence (Anthropic Claude). AI-
            generated content may contain errors, omissions, or inaccuracies. You should review all generated documents
            carefully before using them.
          </p>

          <h2 className="text-xl font-bold text-[#1a2744] mt-8 mb-3">No guaranteed outcome</h2>
          <p className="text-gray-700 mb-4">
            Using ClaimPilot does not guarantee a specific insurance claim outcome. We do not make representations about
            the likelihood of your claim succeeding or the amount you may receive.
          </p>

          <h2 className="text-xl font-bold text-[#1a2744] mt-8 mb-3">Seek professional advice</h2>
          <p className="text-gray-700 mb-4">
            For regulated advice on your insurance claim, consult one or more of the following:
          </p>
          <ul className="list-disc list-inside text-gray-700 mb-4 space-y-2">
            <li>A qualified solicitor with insurance or property law experience</li>
            <li>A licenced public loss adjuster</li>
            <li>A licenced insurance professional or broker</li>
            <li>Your national financial ombudsman or regulator</li>
          </ul>

          <h2 className="text-xl font-bold text-[#1a2744] mt-8 mb-3">Policy interpretation</h2>
          <p className="text-gray-700">
            Insurance policy interpretation is complex and jurisdiction-specific. The analysis provided by ClaimPilot is
            based on the text you upload and should not be taken as a definitive legal interpretation of your policy. Your
            insurer’s or a court’s interpretation may differ.
          </p>
        </div>
      </main>
      <Footer />
    </div>
  )
}
